name: Go grpc CI

on:
  push:
    branches: ["main"]
  pull_request:

# Даем боту права на запись в репозиторий
permissions:
  contents: write

jobs:
  test-and-generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install protoc plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

      - name: Generate gRPC code
        run: |
          rm -rf gen/go
          mkdir -p gen/go
          
          GOPATH_BIN=$(go env GOPATH)/bin
          
          protoc \
            --plugin=protoc-gen-go=$GOPATH_BIN/protoc-gen-go \
            --plugin=protoc-gen-go_grpc=$GOPATH_BIN/protoc-gen-go-grpc \
            --proto_path=api/proto \
            --go_out=. \
            --go_opt=module=github.com/ebairamo/lib-proto3 \
            --go_grpc_out=. \
            --go_grpc_opt=module=github.com/ebairamo/lib-proto3 \
            api/proto/lib/v1/*.proto

      - name: Commit AND Push to ebairamo Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gen/go/
          if git diff --staged --quiet; then
            echo "no generated changes"
          else
            git commit -m "updated grpc code"
            git push
          fi